# Site settings
title: Tech Policy
description: Tech Policy will return...
url: "https://techpolicy.io"
enforce_ssl: techpolicy.io
permalink: /blog/:title/
future: true

# Build settings
markdown: kramdown
sass:
  sourcemap: never